# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FuelCostCalculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FuelCostCalculator

pod 'GoogleMaps', '8.2.0'

  target 'FuelCostCalculatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FuelCostCalculatorUITests' do
    # Pods for testing
  end

end
